### ISSUE TITLE
Supporting Scoped Packages

### ISSUE THREAD

**Issue by mattdesl** [jfhbrook/wzrd.in#104]
I have the following scoped package:
https://www.npmjs.com/package/@mattdesl/raf

But the following gives me an error:
https://wzrd.in/standalone/@mattdesl/raf@latest

```Cannot GET /standalone/mattdesl/raf@latest```

**Comment by DylanPiercey** [comment]
+1

**Comment by Frikki** [comment]
Ignored?

**Comment by jfhbrook** [comment]
Insofar as I don't realistically have time to implement all feature requests? Sure. But feel free to make a pull request and I'd be happy to review.

**Comment by TatumCreative** [comment]
It looks like the registry isn't listing the metadata from the registry for scoped packages.

| where | status | url |
| -------- | -------- | ---- |
| Non-scoped | found | http://registry.npmjs.org/color |
| Scope | not found | http://registry.npmjs.org/@tatumcreative/color |
| Tarball | found | http://registry.npmjs.org/@tatumcreative/color/-/color-1.1.3.tgz |

I might try and find where this is in the registry code...

**Comment by TatumCreative** [comment]
Got it! http://registry.npmjs.com/@tatumcreative%2Fcolor

**Comment by tomekwi** [comment]
https://wzrd.in/standalone/@mattdesl%2Fraf@latest still doesn’t work though.

**Comment by TatumCreative** [comment]
#112 resolves this and adds scoped module support.

**Comment by jfhbrook** [comment]
Thanks @TatumCreative ! I'm experimenting with the http://openopensource.org thing so you're a collaborator now. Cheers!

**Comment by TatumCreative** [comment]
Oh sweet, I've been thinking about trying that out myself.

**Comment by tomekwi** [comment]
Wooohooo! Great news!

:dancers: :dancers: :dancers:
