### ISSUE TITLE
GET /multi seems to be broken

### ISSUE THREAD

**Issue by alexlincoln** [jfhbrook/wzrd.in#108]
The following seems to be generated trying to run the example (https://wzrd.in/multi/48GOmL0XvnRZn32bkpz75A==) or any url

```TypeError: Property 'multibundles' of object #<Object> is not a function at /home/admin/browserify-cdn/multiple.js:135:11 at callbacks (/home/admin/browserify-cdn/node_modules/express/lib/router/index.js:164:37) at param (/home/admin/browserify-cdn/node_modules/express/lib/router/index.js:138:11) at param (/home/admin/browserify-cdn/node_modules/express/lib/router/index.js:135:11) at pass (/home/admin/browserify-cdn/node_modules/express/lib/router/index.js:145:5) at Router._dispatch (/home/admin/browserify-cdn/node_modules/express/lib/router/index.js:173:5) at Object.router (/home/admin/browserify-cdn/node_modules/express/lib/router/index.js:33:10) at next (/home/admin/browserify-cdn/node_modules/express/node_modules/connect/lib/proto.js:193:15) at resume (/home/admin/browserify-cdn/node_modules/express/node_modules/connect/lib/middleware/static.js:65:7) at SendStream.error (/home/admin/browserify-cdn/node_modules/express/node_modules/connect/lib/middleware/static.js:80:37)```

**Comment by jfsiii** [comment]
I first saw this in February, but it's remained an issue every time I've checked since then https://twitter.com/JFSIII/status/564880648377073664

**Comment by jfhbrook** [comment]
I think I fixed this.

**Comment by jfhbrook** [comment]
At the least, this now properly calls `Cache#get`.
