### ISSUE TITLE
Support for setting the entry point when bundling standalone

### ISSUE THREAD

**Issue by Risto-Stevcev** [jfhbrook/wzrd.in#124]
Sometimes it's useful to be able to choose the entry point when bundling the browserify standalone.
Some npm modules have multiple entry points, such as [snabbdom](https://www.npmjs.com/package/snabbdom)

**Comment by jfhbrook** [comment]
Should be good to go. https://wzrd.in/standalone/snabbdom%2Fmodules%2Fclass
