### ISSUE TITLE
 http://wzrd.in  is 502

### ISSUE THREAD

**Issue by monkindey** [jfhbrook/wzrd.in#143]
the wzrd website is awesome, but it doesn't work and return 502 Bad Gateway error

**Comment by CrossEye** [comment]
Any help needed with this?  Coding, time, hosting, cash?

**Comment by jfhbrook** [comment]
should be okay now

**Comment by jfhbrook** [comment]
See: https://github.com/jfhbrook/wzrd.in/issues/103

**Comment by jfhbrook** [comment]
@crosseye if you wanna help, find me a copypaste-able logrotate config

**Comment by CrossEye** [comment]
@buzzdecafe has said he'd try.  If he doesn't have anything before then, I will look into logrotate this evening.  It's been a long time for me, though, too.
