### ISSUE TITLE
wzrd.in certificate has expired

### ISSUE THREAD

**Issue by Pete77** [jfhbrook/wzrd.in#147]
The SSL Certificate has apparently expired for wzrd.in.

**Comment by voronianski** [comment]
@jfhbrook is it possible to fix this ASAP?

**Comment by jfhbrook** [comment]
I've been trying to ping @maxogden who I believe knows much more about the ssl certs than I do. I have admin on the box but did not set up ssl.

**Comment by jfhbrook** [comment]
@konklone maybe you know about this? I found https://github.com/jfhbrook/wzrd.in/issues/78 this issue about https, maybe you helped set it up?

**Comment by jfhbrook** [comment]
I did some mild investigation--it's letsencrypt. It looks like an older version of letsencrypt, so this might involve me doing some surgery.

**Comment by jfhbrook** [comment]
Hey, I think I fixed it! Can you confirm @voronianski ?

I dumped certbot-auto into the homedir, ran it with --nginx and I think that fixed it for now.

Reading to see if I need to cron job this.

**Comment by jfhbrook** [comment]
Added `certbot --nginx renew` to the crontab, I think this'll make the problem go away for a while.

**Comment by voronianski** [comment]
@jfhbrook works! Thanks a lot!

**Comment by jfhbrook** [comment]
alright closing then

**Comment by bloodyKnuckles** [comment]
Has the SSL cert expired?

https://www.sslshopper.com/ssl-checker.html#hostname=wzrd.in

I'm getting "Error: CORS request rejected: https://wzrd.in/multi" error on esnextb.in
