### ISSUE TITLE
wzrd.in is down

### ISSUE THREAD

**Issue by ArtskydJ** [jfhbrook/wzrd.in#155]
Just letting you know that wzrd.in has been down for about 30 minutes now.

**Comment by Draccan** [comment]
Can I ask you to resolve the problem as soon as possible?

**Comment by jfhbrook** [comment]
I'm at work and ssh is timing out, so there isn't much I can do.

Pinging @maxogden who might be able to do something from the host's dashboard.

**Comment by ArtskydJ** [comment]
It's fixed now.
