### ISSUE TITLE
Cannot GET /standalone/deepfreeze@latest

### ISSUE THREAD

**Issue by gpspake** [jfhbrook/wzrd.in#158]
I discovered wzrd.in through dan abramov's ["Getting Started with Redux"](https://egghead.io/courses/getting-started-with-redux) course on egghead.io, which I expect might be the case for a lot of people, and I primarily use it to load in the 'expect' and 'deepfreeze' libraries. As far as I can tell, deepfreeze isn't hosted on any other cdn.

Until yesterday, the following worked fine:
```
<script src="https://wzrd.in/standalone/expect@latest"></script>
<script src="https://wzrd.in/standalone/deepfreeze@latest"></script>
```
but after #157 was fixed, (not sure if this is related) I get the following:
```
https://wzrd.in/standalone/expect@latest
Cannot GET /standalone/expect@latest

https://wzrd.in/standalone/deepfreeze@latest
Cannot GET /standalone/deepfreeze@latest
```
So that's going to break for anyone following along with that course now and I use these in a bunch of jsbin examples I share with people pretty regularly. Is this something that will be fixed? Has something changed? Do I have a bad url?

**Comment by jfhbrook** [comment]
Looks like a all standalones are breaking.

#157 is probably related somehow? The only change to the codebase I made was https://github.com/jfhbrook/wzrd.in/commit/7fd0c033b00e1b4ba5d7752064bfe7c68e0463bf which I wouldn't expect to cause problems, but who knows. The weird thing is that this appeared to be working last night.

I'm at work right now so it's gonna be about 8 hrs before I can look. I apologize for the inconvenience.

**Comment by jfhbrook** [comment]
This appears fixed.

I believe the issue centered around a borked npm install that happened when I deployed the decreased TTL change. I'm not sure why the site appeared to work last night but wasn't today. :) but it should be better now!

Again, apologies!

**Comment by gpspake** [comment]
Woo! no worries, thanks for fixing 😎

**Comment by aksswami** [comment]
Standalones are not working, as of now.

**Comment by jfhbrook** [comment]
Bigger problem than that. https://github.com/browserify/wzrd.in/issues/186

**Comment by arnaudambro** [comment]
By the way, I copy-pasted your code in my JS Bin, and you made a mistake forgetting a - :
`<script src="https://wzrd.in/standalone/deep*-*freeze@latest"></script>`

**Comment by vincentdd** [comment]
I have the same problem.
---FLAGRANT SYSTEM ERROR---

(logs uuid: db3ad680-6660-11e8-9c06-47f75f07dbf4 )

Error: "npm registry returned status code 404"

body: { error: 'Not found' }

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!

how can i use deepfreeze by CDN plz..

**Comment by zavex** [comment]
Looks like a all standalones are still breaking. Where should I look ???

**Comment by zavex** [comment]
I just found this one 
<script src="https://cdnjs.cloudflare.com/ajax/libs/expect/1.20.2/expect.min.js"></script>
...
The deepfreeze its just to make more clear the mutations topic, however , for usefull practices, you just need expect and u can go from there 

Happy coding !
