### ISSUE TITLE
service is 502 Bad Gateway

### ISSUE THREAD

**Issue by balupton** [jfhbrook/wzrd.in#165]
![screen shot 2017-04-01 at 5 01 40 am](https://cloud.githubusercontent.com/assets/61148/24569379/5e3c7544-1698-11e7-8921-f579163c7c4e.png)

**Comment by jfhbrook** [comment]
you don't need to send screenshots, I'll take you at your word.

In the short term, it appears up for the moment.

In the long term, read the story at https://twitter.com/jfhbrook/status/847620322563997697 and I'll see if I can figure this one out over the weekend.

**Comment by jfhbrook** [comment]
I also reconfigured logrotate to rotate hourly, retain only logs for 12hrs out and use compression. This should help.

**Comment by jfhbrook** [comment]
I also 429'd the offending "user" in the app layer. Not where I wanted it, but better than recompiling nginx on a live server. :/

I'll re-open this if it's re-reported but, fingers crossed.

**Comment by balupton** [comment]
Cool. Good to hear. Well done making that decision

**Comment by fabb** [comment]
It's down again

**Comment by balupton** [comment]
@fabb from my understanding, this repo is no longer maintained, use jspm.io or unpkg.com as alternatives

**Comment by fabb** [comment]
Hmm, I guess then requirebin.com should no longer use this?
