### ISSUE TITLE
wzrd.in SSL breaking change?

### ISSUE THREAD

**Issue by robbiemu** [jfhbrook/wzrd.in#168]
Im noticing, over the past few hours a change has occurred where the site is inaccessible over https. both the actual website and the served libraries, which note in the log: `Failed to load resource: net::ERR_INSECURE_RESPONSE`

**Comment by jfhbrook** [comment]
Most likely the letsencrypt cron job is broken. I'll take a look.

**Comment by jfhbrook** [comment]
Looks better now. I think the job was failing because of \*sigh\* disk problems.
