### ISSUE TITLE
How to reference submodules within a package?

### ISSUE THREAD

**Issue by broofa** [jfhbrook/wzrd.in#171]
Over at https://github.com/kelektiv/node-uuid we're moving our API in the direction of having callers require submodules directly rather than exposing them in a combined top-level import.  E.g. `require('uuid/v4')` is now preferred over `require('uuid').v4`.  This provides better dependency decoupling.

It would be nice if wzrd.in supported similar notation.  E.g. `https://wzrd.in/standalone/uuid@latest/v4`

**Comment by jfhbrook** [comment]
https://wzrd.in/standalone/uuid%2Fv4@latest
