### ISSUE TITLE
wzrd.in appears to be down

### ISSUE THREAD

**Issue by ShortyFR** [jfhbrook/wzrd.in#172]
URLs on wzrd.in are not responding, once again.

**Comment by bloodyKnuckles** [comment]
Has the SSL cert expired?

https://www.sslshopper.com/ssl-checker.html#hostname=wzrd.in

I'm getting "Error: CORS request rejected: https://wzrd.in/multi" error on esnextb.in

**Comment by konklone** [comment]
No, visiting https://wzrd.in/multi just doesn't connect if you try and visit it in a browser. Looks like a server/deployment configuration issue.

**Comment by jfhbrook** [comment]
Sorry friends, I think I've exhausted all my options for debugging this. I can try again in a little bit and see if it's a weird freak thing, but if I can't get into the box I can't really do anything about it.

Sorry again.

**Comment by bloodyKnuckles** [comment]
Yay! Back online: https://wzrd.in/
My exnextbin works too. :)

**Comment by jfhbrook** [comment]
I, uh, works for me! Maybe max rebooted it.

**Comment by Masterxilo** [comment]
It is down again.

**Comment by jpazmino-work** [comment]
Is it down today
